# 基于微服务的 configserver 默认配置修改
#服务名称：
  #具体配置：
    #...
spring:
  cache:
    type: redis
    database: 1
  redis:
    host: localhost
    port: 6379
    timeout: 36000
    database: 0
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sim-basic?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: flowable
    password: flowable
    driverClassName: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
    useGlobalDataSourceStat: useGlobalDataSourceStat
    initialSize: 20
    minIdle: 20
    maxActive: 2000
    maxWait: 180000
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.sim.common.entity #批量增设别名
  config-location: classpath:config/mybatis-config.xml
mapper:
  mappers: com.sim.common.util.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 180000