# 基于微服务的 configserver 默认配置修改
#服务名称：
  #具体配置：
    #...
spring:
  cache:
    type: redis
    database: 1
  redis:
    host: localhost
    port: 6379
    timeout: 36000
    database: 0
    password:
  datasource:
    username: flowable
    password: flowable
    url: jdbc:mysql://127.0.0.1:3306/sim-basic?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: {stat,wall,log4j}
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.sim.common.entity #批量增设别名
  config-location: classpath:config/mybatis-config.xml
mapper:
  mappers: com.sim.common.util.mybatis.MyMapper
  not-empty: false
  identity: MYSQL
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 180000