spring:
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/sim-basic?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: flowable
      password: '{cipher}AQA3bH+Y12eJEhO9muVXAcMnGn3uJJ5DyMHHyub4RpIaJIoUyXNaFLkZoKu3iNblt06Gj3pMTjqlgKW2rzVca7e9kDnn3ZqrcfdELuRCFLXrvDKaXh2z5L3Z9u6DKkiJWRcI+XSaBz6lXjwR4rLBw3n6908+Ulm6sX2jCoUmz0siU/Im3etX5pISBJSTQMjRdgsKw6J4uThuYy37zgRJXsQrlCPRUNA5w5Hn/6AtNVzJHOx51cqGteP2wiaThCA9k7q1D7b3n9mCnZX52nN++vBsU3XDYvyHqtFR2U7jS2OqLpachW7ibo+M3n2xPmNigi9NG4jEjg48EVk1SiuKRNg8q2fMByuWKYnCVstehE5giP6feoltwq6NBzk7dPmcKmE='
      filters: stat,wall,log4j,config
      max-active: 2000
      initial-size: 20
      max-wait: 180000
      min-idle: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
  cache:
    type: redis
    database: 1
  redis:
    host: localhost
    port: 6379
    timeout: 36000
    database: 0
    password: '{cipher}AQBOoAEywUw7oEmdy2w/9h3OQEo1OzcQ6jWkNuemUYopmyOoMwnhLIaTDuBTbA6nc1yVRQWV597JxtobZk+3B7hRBtpiUKJ/Fgx8QMz38iKIe/wJzhxEfDKwZQ2FQ/L2BJ31L1yp9UnYh2CupEVwhuT+HgDzwZ1CzYrp4G1a3q8WCvkjt18MDJtiYkP1ZagxcD6muTauPVWp9UiaRHAQGKlsuugRpI0WLrLFbV1nym2dmdfQwkfy2+L/hqCBnf8aSiqJNE0EAYAT4LsQOqk8GzmskDJPgBvul4WHIOFRf4wUBj0HEWyXLNby4KzcmNMWUy/CSlDRXejNZpJ9BTIEPnIxYnpmHiBwiXJMHioLFcms40cyJyBg0+A2jSGRXWRUAET+/gR2CJ/n9DGVpoQulWVl'   
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2183
          defaultZkPort: 2183    
mybatis:
  mapperLocations: classpath:mapping/*.xml
  type-aliases-package: com.sim.common.entity #批量增设别名
  config-location: classpath:config/mybatis-config.xml
mapper:
  mappers: com.sim.common.util.mybatis.SimMapper
  not-empty: false
  identity: MYSQL
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 180000
myname: 'zhanghj07' 
distributedtransaction:
  service:
    name: sim-basic 